"""Angelo Terminez (ater906)"""
import turtle
def draw_shape(t,num,move,x,y):
	
	if num > 1: #draws the shape object in each of the 4 corners of its origin shape
		t.goto(x,y)
		t.down()
		t.forward(move)
		t.left(90)
		t.forward(move)
		t.up()
		t.backward(move)
		t.down()
		t.backward(move)
		t.up()
		t.goto(x,y)
		t.down()
		t.left(90)
		t.forward(move)
		t.left(90)
		t.forward(move)
		t.up()
		t.backward(move)
		t.down()
		t.backward(move)
		t.up()
		
		t.left(90)
		
		t.goto(x,-y)
		t.down()
		t.forward(move)
		t.left(90)
		t.forward(move)
		t.up()
		t.backward(move)
		t.down()
		t.backward(move)
		t.up()
		t.goto(x,-y)
		t.down()
		t.left(90)
		t.forward(move)
		t.left(90)
		t.forward(move)
		t.up()
		t.backward(move)
		t.down()
		t.backward(move)
		t.up()

		t.left(90)

		t.goto(-x,-y)
		t.down()
		t.forward(move)
		t.left(90)
		t.forward(move)
		t.up()
		t.backward(move)
		t.down()
		t.backward(move)
		t.up()
		t.goto(-x,-y)
		t.down()
		t.left(90)
		t.forward(move)
		t.left(90)
		t.forward(move)
		t.up()
		t.backward(move)
		t.down()
		t.backward(move)
		t.up()
		
		t.left(90)
		
		t.goto(-x,y)
		t.down()
		t.forward(move)
		t.left(90)
		t.forward(move)
		t.up()
		t.backward(move)
		t.down()
		t.backward(move)
		t.up()
		t.goto(-x,y)
		t.down()
		t.left(90)
		t.forward(move)
		t.left(90)
		t.forward(move)
		t.up()
		t.backward(move)
		t.down()
		t.backward(move)
		t.up()
		
		t.left(90)
		draw_shape(t,num-1,move//2,x//2,y//2) # this so when the shape num == 1 it goes to the elif statement
		if num >2: # recursively does this statement until num > 1)
			draw_shape(t,num-1,move//2,x//2+100,y//2 +100)
			draw_shape(t,num-1,move//2,x//2,y//2+100)
			draw_shape(t,num-1,move//2,x//2+100,y//2)
		
	elif num == 1: # this is the original size of the shape (first level)
		t.goto(0,0)
		t.down()
		t.forward(100)
		t.left(90)
		t.forward(100)
		t.up()
		t.backward(100)
		t.down()
		t.backward(100)
		t.up()
		t.goto(0,0)
		t.down()
		t.left(90)
		t.forward(100)
		t.left(90)
		t.forward(100)
		t.up()
		t.backward(100)
		t.down()
		t.backward(100)
		t.up()
		t.goto(0,0)
		t.left(90)
		
def q1():
	my_win = turtle.Screen()
	my_turtle = turtle.Turtle()
	my_turtle.speed(0)
	my_turtle.left(90)
	my_turtle.up()
	n = int(input('Draw shape at level: '))
	draw_shape(my_turtle,n,50,100,100)
	my_win.exitonclick()

q1()

